#!/bin/bash

/usr/bin/rsync -rvP --stats /data/Diana/test1 /mnt/diana_nas  --exclude=lost+found --exclude="*.db-journal" --exclude="*.zip" --exclude="*.db.*"

#/usr/bin/rsync -rvP  /data/Diana/everything_else /mnt/diana_nas --exclude=lost+found --exclude="*.db-journal" --exclude="*.zip" --exclude="*.db.*"
